name: Build_development

on:
  workflow_dispatch:      # Start a workflow
  push:
    branches: main
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes
    - 'tasmota/berry/**'  # Ignore Berry examples

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  be_solidify:
    runs-on: ubuntu-latest
    if: github.repository == 'TanNhatCMS/Tasmota' && github.ref_name == 'main'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Make Berry and Solidify code
        run: |
          cd lib/libesp32/berry
          make
          cd ../berry_tasmota
          ../berry/berry -s -g solidify_all.be
          cd ../berry_matter
          ../berry/berry -s -g solidify_all.be
          cd ../berry_animation
          ../berry/berry -s -g solidify_all.be
          cd ../../libesp32_lvgl/lv_binding_berry
          ../../libesp32/berry/berry -s -g solidify_all.be
          cd ../lv_haspmota
          ../../libesp32/berry/berry -s -g solidify_all.be
      - uses: actions/upload-artifact@v4
        with:
          name: berry
          path: |
            ./lib/libesp32/berry_tasmota/src/solidify
            ./lib/libesp32/berry_matter/src/solidify
            ./lib/libesp32/berry_animation/src/solidify
            ./lib/libesp32_lvgl/lv_binding_berry/src/solidify
            ./lib/libesp32_lvgl/lv_haspmota/src/solidify
            ./lib/libesp32/berry/generate

  push_solidified:
    needs: be_solidify
    runs-on: ubuntu-latest
    if: github.repository == 'TanNhatCMS/Tasmota' && github.ref_name == 'main'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: actions/download-artifact@v4
        with:
          pattern: berry
          path: berry
      - name: Move solidified Berry files back
        run: |
          ls -R ./berry
          mv berry/berry/libesp32/berry_tasmota/src/solidify/* ./lib/libesp32/berry_tasmota/src/solidify
          mv berry/berry/libesp32/berry_matter/src/solidify/* ./lib/libesp32/berry_matter/src/solidify
          mv berry/berry/libesp32/berry_animation/src/solidify/* ./lib/libesp32/berry_animation/src/solidify
          mv berry/berry/libesp32_lvgl/lv_binding_berry/src/solidify/* ./lib/libesp32_lvgl/lv_binding_berry/src/solidify
          mv berry/berry/libesp32_lvgl/lv_haspmota/src/solidify/* ./lib/libesp32_lvgl/lv_haspmota/src/solidify
          mv berry/berry/libesp32/berry/generate/* ./lib/libesp32/berry/generate
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Solidified Code updated

  safeboot-images:
    needs: push_solidified
    runs-on: ubuntu-latest
    if: github.repository == 'TanNhatCMS/Tasmota'
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota32-safeboot
          - tasmota32solo1-safeboot
          - tasmota32s2-safeboot
          - tasmota32s2cdc-safeboot
          - tasmota32s3-safeboot
          - tasmota32s3ser-safeboot
          - tasmota32c2-safeboot
          - tasmota32c3-safeboot
          - tasmota32c3ser-safeboot
          - tasmota32c5-safeboot
          - tasmota32c5ser-safeboot
          - tasmota32c6-safeboot
          - tasmota32c6ser-safeboot
          - tasmota32p4-safeboot
          - tasmota32p4ser-safeboot
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system platformio
          cp ./platformio_override_sample.ini ./platformio_override.ini
      - name: Add SHA to footer
        run: |
          COMMIT_SHA_LONG=$(git rev-parse --short HEAD || echo "")
          SHA=${COMMIT_SHA_LONG::7}
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT $SHA-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e ${{ matrix.variant }} 
      - name: Upload safeboot firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant }}
          path: ./build_output

  base-images:
    needs: push_solidified
    runs-on: ubuntu-latest
    if: github.repository == 'TanNhatCMS/Tasmota'
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota
          - tasmota-4M
          - tasmota-minimal
          - tasmota-display
          - tasmota-ir
          - tasmota-knx
          - tasmota-lite
          - tasmota-sensors
          - tasmota-zbbridge
          - tasmota-zigbee
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system platformio
      - name: Add SHA to footer
        run: |
          COMMIT_SHA_LONG=$(git rev-parse --short HEAD || echo "")
          SHA=${COMMIT_SHA_LONG::7}
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT $SHA-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e ${{ matrix.variant }}
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant }}
          path: ./build_output

  base32-images:
    needs: safeboot-images
    runs-on: ubuntu-latest
    if: github.repository == 'TanNhatCMS/Tasmota'
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota32
          - tasmota32-zbbrdgpro
          - tasmota32-webcam
          - tasmota32-bluetooth
          - tasmota32-nspanel
          - tasmota32-display
          - tasmota32-ir
          - tasmota32-lvgl
          - tasmota32c2
          - tasmota32c3
          - tasmota32c5
          - tasmota32c6
          - tasmota32p4
          - tasmota32s2
          - tasmota32s2cdc
          - tasmota32s3
          - tasmota32solo1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system platformio
          cp ./platformio_override_sample.ini ./platformio_override.ini
      - name: Download safeboot firmwares
        uses: actions/download-artifact@v4
        with:
          pattern: tasmota32*
          path: ./temp
      - name: Move safeboot files
        run: |
          mkdir -p ./firmware/firmware
          find ./temp -type f -exec cp -t ./firmware/firmware {} +
      - name: Add SHA to footer
        run: |
          COMMIT_SHA_LONG=$(git rev-parse --short HEAD || echo "")
          SHA=${COMMIT_SHA_LONG::7}
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT $SHA-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e ${{ matrix.variant }}
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant }}
          path: ./build_output

  thingsboard-images:
    needs: safeboot-images
    runs-on: ubuntu-latest
    if: github.repository == 'TanNhatCMS/Tasmota'
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota1M-thingsboard
          - tasmota32-thingsboard
          - tasmota32s3psram-thingsboard
          - tasmota32c3-thingsboard
          - tasmota1M-thingsboard-VN
          - tasmota32-thingsboard-VN
          - tasmota32s3psram-thingsboard-VN
          - tasmota32c3-thingsboard-VN
          - tasmota32s3psram-thingsboard-lite
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system platformio
          cp ./platformio_override_sample.ini ./platformio_override.ini
          cp ./platformio_tasmota_cenv_thingsboard.ini ./platformio_tasmota_cenv.ini
      - name: Select user config override
        run: |
          if [ "${{ matrix.variant }}" = "tasmota32s3psram-thingsboard-lite" ]; then
            echo "Using lite config"
            cp ./tasmota/user_config_override_lite.h ./tasmota/user_config_override.h
          else
            echo "Using full config"
            cp ./tasmota/user_config_override_full.h ./tasmota/user_config_override.h
          fi
      - name: Download safeboot firmwares
        uses: actions/download-artifact@v4
        with:
          pattern: tasmota32*
          path: ./temp
      - name: Move safeboot files
        run: |
          mkdir -p ./firmware/firmware
          find ./temp -type f -exec cp -t ./firmware/firmware {} +
      - name: Add SHA to footer
        run: |
          COMMIT_SHA_LONG=$(git rev-parse --short HEAD || echo "")
          SHA=${COMMIT_SHA_LONG::7}
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT $SHA-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e ${{ matrix.variant }}
      - name: Upload language firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant }}
          path: ./build_output

  # Start_final_copy:
  #   needs: [base-images, base32-images, language-images]
  #   runs-on: ubuntu-latest
  #   env:
  #     GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
  #   steps:
  #   - name: Dispatch workflow in TanNhatCMS/Tasmota-firmware
  #     run: |
  #       gh api repos/TanNhatCMS/Tasmota-firmware/actions/workflows/fetch_deploy.yml/dispatches \
  #         --method POST \
  #         -f ref='gh_actions'
